# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

## Exercise 1.1 install Numpy

In [1]:
!pip install Numpy

## Exercise 1.2 # Import Numpy package

In [3]:
import numpy as np

## Exercise 1.3 ## Example 

In [9]:
data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


## Exercise 1.4 Do all exercises from Lecture slides

### import numpy

In [12]:
import numpy
arr = numpy.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


### Create 2-D array

In [16]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr)

[[10 20 30]
 [40 50 60]]


### Get the first element from the following array

In [23]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])

10


### Slice elements from index 1 to index 5 from the following array

In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


### Sort the array in Numpy

In [33]:
import numpy as np
arr = np.array([30, 20, 40, 10])
print(np.sort(arr))

[10 20 30 40]


### Sort the array alphabetically

In [36]:
import numpy as np
arr = np.array(['kiwi', 'berry', 'pear'])
print(np.sort(arr))

['berry' 'kiwi' 'pear']


## Exercise 1.5 Searching Arrays - find method of numpy to search an element in array
### Find the indexes where the value is 9: arr = np.array([3, 2, 14, 9, 10, 12])

In [44]:
arr = np.array([3, 2, 14, 9, 10, 12])
indices = np.where(arr == 9)
print(indices)

(array([3], dtype=int64),)


### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

In [51]:
arr1 = np.array([9, 5, 8])
arr2 = np.array([55, 89, 76])
arr = np.concatenate((arr1, arr2))
print(arr)

[ 9  5  8 55 89 76]
